#!/bin/bash

# Base script generated by NERSC Batch Script Generator on https://iris.nersc.gov/jobscript.html

#SBATCH -N 1
#SBATCH -C gpu
#SBATCH -G 1
#SBATCH -q debug
#SBATCH -A deepsrch_g
#SBATCH -t 0:30:0

# OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

# Set up conda env
module load python
source activate $HOME/conda_envs/vit_env_0

# Set up paths
GS_DIR="/pscratch/sd/a/amurr1/Roman-lens-search/alexisMurray/TransformerExploration/EffFormerV2S0_tf/GridSearchTest"
CSV_PATH="$GS_DIR/TrainingLogs/train_log_${DS}_${LR}_${BS}_${SLURM_JOB_ID}.csv"
CHKPT_PATH="$GS_DIR/Weights/BestChkpt/chkpt_${DS}_${LR}_${BS}_${SLURM_JOB_ID}.h5"
END_PATH="$GS_DIR/Weights/EndRun/endrun_${DS}_${LR}_${BS}_${SLURM_JOB_ID}.h5"

#run the application: 
# applications may perform better with --gpu-bind=none instead of --gpu-bind=single:1
srun -n 1 -c 128 --cpu_bind=cores -G 1 --gpu-bind=single:1 python /pscratch/sd/a/amurr1/Roman-lens-search/alexisMurray/TransformerExploration/EffFormerV2S0_tf/GridSearchTest/train_efv2s0.py --ds $DS --lr $LR --bs $BS --log_csv "$CSV_PATH" --w_chkpt "$CHKPT_PATH" --w_end "$END_PATH"