#!/bin/bash

# Base script generated by NERSC Batch Script Generator on https://iris.nersc.gov/jobscript.html

#SBATCH -N 1
#SBATCH -C gpu
#SBATCH -G 4
#SBATCH -q regular
#SBATCH -A deepsrch_g
#SBATCH -t 0:30:0

# OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

# Set up conda env
module load python
source /global/common/software/nersc/pe/conda/24.10.0/Miniforge3-24.7.1-0/etc/profile.d/conda.sh
conda activate $HOME/conda_envs/vit_env_0

# Set up paths
GS_DIR="/pscratch/sd/a/amurr1/Roman-lens-search/alexisMurray/TransformerExploration/EffFormer/EffFormerSearch"
CSV_PATH="$GS_DIR/TrainingLogs/train_log_${MODEL}_${SLURM_JOB_ID}.csv"
CHKPT_PATH="$GS_DIR/Weights/BestChkpt/chkpt_${MODEL}_${SLURM_JOB_ID}.h5"
END_PATH="$GS_DIR/Weights/EndRun/endrun_${MODEL}_${SLURM_JOB_ID}.h5"

#run the application: 
# applications may perform better with --gpu-bind=none instead of --gpu-bind=single:1
srun -n 1 -c 1 --cpu_bind=cores -G 4 --gpu-bind=map_gpu:0,1,2,3 $(which python) /pscratch/sd/a/amurr1/Roman-lens-search/alexisMurray/TransformerExploration/EffFormer/EffFormerSearch/train_ef.py --model $MODEL --log_csv "$CSV_PATH" --w_chkpt "$CHKPT_PATH" --w_end "$END_PATH"